"""Giao ước hiển thị của agent. Vòng làm việc và công cụ không phụ thuộc cách vẽ terminal."""

from __future__ import annotations

from typing import Protocol


class ReplyView(Protocol):
    started: bool

    def feed(self, text: str) -> None: ...
    def finish(self) -> None: ...


class AgentUI(Protocol):
    def line(self, text: str = "", color: str | None = None) -> None: ...
    def step(self, text: str) -> None: ...
    def plan(self, steps: list[dict]) -> None: ...
    def success(self, text: str) -> None: ...
    def failure(self, text: str) -> None: ...
    def status(self, text: str) -> None: ...
    def bell(self) -> None: ...
    def title(self, text: str) -> None: ...
    def clear_status(self) -> None: ...
    def reply(self) -> ReplyView: ...
    def diff(self, title: str, before: str, after: str) -> None: ...
    def review_diff(self, title: str, before: str, after: str) -> None: ...
    def ask_permission(self, *, allow_session: bool = False, allow_always: bool = False,
                       session_label: str = ..., question: str = ...) -> str: ...
    def page_permission(self, origin: str, action: str) -> None: ...
    def site_permission(self, url: str, site: str, unusual: bool = False) -> None: ...
    def hand_over(self, reason: str) -> None: ...
    def wait_for_user(self) -> bool: ...
    def item(self, text: str) -> None: ...
    def page(self, title: str, details: str, problems: list[str], *, path: str | None = None) -> None: ...
    def command(self, command: str, directory: str, timeout: int, *, shell: str = "cmd",
                background: bool = False) -> None: ...
    def command_progress(self, seconds: float, output: str) -> None: ...
    def command_result(self, result: dict) -> None: ...
